const ICONS = {
  arrowDown: 'ArrowDown',
  arrowLeft: 'ArrowLeft',
  arrowRight: 'ArrowRight',
  arrowUp: 'arrowUp',
  blockquote: 'Blockquote',
  bold: 'Bold',
  calendar: 'Calendar',
  check: 'Check',
  checkCircle: 'CheckCircle',
  chevronDown: 'ChevronDown',
  chevronLeft: 'ChevronLeft',
  chevronRight: 'ChevronRight',
  chevronUp: 'ChevronUp',
  close: 'Close',
  cog: 'Cog',
  edit: 'Edit',
  github: 'Github',
  image: 'Image',
  italic: 'Italic',
  ol: 'Ol',
  page: 'Page',
  people: 'People',
  person: 'Person',
  plus: 'Plus',
  poll: 'Poll',
  posts: 'Posts',
  remove: 'Remove',
  ul: 'Ul',
  underline: 'Underline',
};
export default ICONS;
