const ICONS = {
  posts: 'Posts',
  people: 'People',
  page: 'Page',
  cog: 'Cog',
  bold: 'Bold',
  italic: 'Italic',
  underline: 'Underline',
  quotes: 'Quotes',
  ul: 'Ul',
  ol: 'Ol',
  checkCircle: 'CheckCircle',
  calendar: 'Calendar',
  person: 'Person',
  image: 'Image',
  poll: 'Poll',
  edit: 'Edit',
  chevronDown: 'ChevronDown',
  chevronLeft: 'ChevronLeft',
  chevronRight: 'ChevronRight',
  chevronUp: 'ChevronUp',
};
export default ICONS;
